spring:
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5435/inventory_db}
    username: ${INVENTORY_DB_USERNAME:ecommerce}
    password: ${INVENTORY_DB_PASSWORD:ecommerce}

logging:
  file:
    name: ${LOG_FILE:logs/inventory-service.log}
